### PR TITLE
Add readme

### PR DESCRIPTION
**Pull request by Zoopers**

### CODE REVIEW

**Comment by drubin** [comment]
Nice work mr! Now you need to make a change on the website.

**Comment by Zoopers** [comment]
For that I need ruby, right?

**Comment by drubin** [comment]
You can just open the index.html file in your browser and edit it and refresh.

**Comment by Zoopers** [comment]
Oh I see. That's easy enough. Do I have to finalize all changes to the site by submitting pull requests to your git page?

**Comment by drubin** [comment]
For now yes. until we move the hosting to point to your git repo.

**Comment by Zoopers** [comment]
Okay, just making sure. I'll make sure to only do pull requests when you're not busy then. :P

**Pull request merged**
